added test and also ran with pytest. tested both function in main.py …
miccheng/test-automation-workshop pull request #2
Opened 2024-09-29 23:05 UTC by Michellebuchiokonicha

…and database.py

2024-09-29 23:07 UTC, Michellebuchiokonicha commented
test created in todo-app-python

2024-09-30 00:25 UTC, miccheng requested changes
Some changes needed.

2024-09-30 00:25 UTC, miccheng commented on todo-backend/todo-app-python/test_todos.db
Should probably add this file to .gitignore

2024-09-30 00:25 UTC, miccheng commented on todo-backend/todo-app-python/venv/bin/Activate.ps1
I think u checked in the venv folder. We don’t actually need this when running in the Devcontainer. Can remove?

Should probably add to .gitignore as well.

2024-09-30 00:38 UTC, Michellebuchiokonicha reviewed
I added test_todos.db and venv to the .gitignore

2024-09-30 01:11 UTC, miccheng commented
LGTM

2024-09-30 01:11 UTC, merged